### ISSUE TITLE
disproportional vertical scroll when zoomed in

### ISSUE THREAD

**Issue by asnav** [afreakyelf/Pdf-Viewer#112]
📝 Describe the Bug:
while zoomed in vertical scroll is disproportional, horizontal scroll works just fine which means zoom is taken into account.
i assume there is an extra pan behavior on top of the basic scroll function which makes it too fast.

📖 Library Version: 2.0.7

🚶 Steps to Reproduce:
Please follow these steps to reproduce the issue:
1. load a pdf file
2. zoom in
3. scroll up or down
4. notice that the view moves faster than your finger

🤔 Expected Behavior:
the view should move along with he pointer (your finger) at the same speed

**Comment by mlilienberg** [comment]
When google started with instant apps i also implemented a library with a similar approach like this. We use it in production without changes since 2019. This library is published and maintained by a former colleague of mine, you find it here: https://github.com/Dmitry-Borodin/pdfview-android. 

I do not want to advertise that library but maybe you can find any technics to improve this one. I was looking into an alternative that is still maintained and has a compose API, but with some weakness like the disproportional scrolling when zoomed I can not use it as a replacement.

So what is the difference? The other library uses a slightly modified clone of [subsampling scale imageview](https://github.com/davemorrissey/subsampling-scale-image-view) to have following benefits:
* Sharp rendering in any zoom level (especially for text and vector drawings)
* Only render the visible rect, so that it can handle documents with thousands of pages without delay or memory issues
* Proportional scroll at any zoom level

Maybe it is possible to merge the concepts of those two libraries.

**Comment by Sasikumars41** [comment]
> 📝 Describe the Bug: while zoomed in vertical scroll is disproportional, horizontal scroll works just fine which means zoom is taken into account. i assume there is an extra pan behavior on top of the basic scroll function which makes it too fast.
> 
> 📖 Library Version: 2.0.7
> 
> 🚶 Steps to Reproduce: Please follow these steps to reproduce the issue:
> 
> 1. load a pdf file
> 2. zoom in
> 3. scroll up or down
> 4. notice that the view moves faster than your finger
> 
> 🤔 Expected Behavior: the view should move along with he pointer (your finger) at the same speed

Scrolling on vertical is not smooth as horizontal scroll after zoom.

**Comment by afreakyelf** [comment]
Hi, The Above issue has been fixed in new release. https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.1.0

Please migrate to Maven central. More here: https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.1.0

Thank you for using the library. Please reopen/raise a new issue if you still face this error.

Join our [discord](https://discord.gg/z9qQSHMxSR) for more updates!

**Comment by Sasikumars41** [comment]
Hi,

 Please slow down the scrolling speed of the scroll after zoom. It works fine on normal state.

**Comment by asnav** [comment]
It has indeed not been fixed.

**Comment by justinmulligan** [comment]
Can this be reopened? 
The vertical scroll still isn't right.
